version: "3.3"

services:

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    command: python -u app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    links:
      - db
  db:
    image: mongo:latest
    hostname: test_mongodb
    environment:
      - MONGO_INITDB_DATABASE=test_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    ports:
      - 27018:27018
  redis:
    image: redis
  celery:
      build:
        context: ./
      command: rm worker.pid
      command: celery -A tasks worker -l info --pidfile=worker.pid
      depends_on:
        - redis
  flower:
    image: mher/flower
    command: ["flower", "--broker=redis://redis:6379/0", "--port=8888"]
    ports:
      - 8888:8888